name: dart_blockchain
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^3.4.0-99.1.beta

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
